on:
  push:
    branches: [ master, maint-1.4 ]

jobs:
  make-wheel-linux-arm64:
    name: Make arm64 binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |
          docker run --rm --privileged hypriot/qemu-register
      - uses: docker://arm64v8/alpine:latest
        with:
          args: 'sh .github/scripts/arm64_test.sh' 
      - run: |
          ls /home/runner/work/jobber/jobber/pkgs
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: alpine-pkg-arm64
          path: pkgs
      - name: Upload wheel manylinux2014 to release
        # upload the generated manylinux2014 wheel to the github release. Only a single file per step can be uploaded at the moment
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # this is a release to the event is called release: https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
          # the release event has the structure of this response https://developer.github.com/v3/repos/releases/#create-a-release
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: pkgs/
          asset_name: alpine-pkg-arm64
          asset_content_type: application/zip # application/octet-stream
