on:
  push:
    branches: [ master, maint-1.4 ]

jobs:
  make-wheel-linux-arm64:
    name: Make arm64 binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |
          docker run --rm --privileged hypriot/qemu-register
      - uses: docker://arm64v8/alpine:latest
        with:
          args: 'sh .github/scripts/arm64_test.sh' 
      - run: |
          ls /home/runner/work/jobber/jobber/pkgs
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: alpine-pkg-arm64
          path: pkgs
      - name: Upload wheel manylinux2014 to release
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: '*.bin'
