on:
  push:
    branches: [ master, maint-1.4 ]

jobs:
  make-wheel-linux-arm64:
    name: Make arm64 binaries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: |
          docker run --rm --privileged hypriot/qemu-register
      - uses: docker://arm64v8/alpine:latest
        with:
          args: 'sh .github/scripts/arm64_test.sh' 
      - run: |
          ls /home/runner/work/jobber/jobber/pkgs
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: alpine-pkg-arm64
          path: pkgs
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: pkgs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
